package PhoenixAdmin::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

use FindBin;
use lib "$FindBin::Bin/../../PhoenixDB/lib";

__PACKAGE__->config(
    schema_class => 'PhoenixDB',
);

=head1 NAME

PhoenixAdmin::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<PhoenixAdmin>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<PhoenixDB>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.54

=head1 AUTHOR

Carl Johnstone

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;